(require-package 'projectile)
(projectile-mode 1)
(setq projectile-project-search-path '("~/Documents/fnlinker/"))
(define-key projectile-mode-map (kbd "s-p") 'projectile-command-map)
(define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
(define-key projectile-mode-map (kbd "C-c C-s") 'projectile-switch-project)
(provide 'init-project)
