(require-package 'projectile)
(projectile-mode 1)
(setq projectile-project-search-path '("~/Documents/fnlinker/" "~/Documents/bwkernel/atlantis-org/" "~/Documents/bwkernel/"))
(define-key projectile-mode-map (kbd "s-p") 'projectile-command-map)
(define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
(define-key projectile-mode-map (kbd "C-c C-p") 'projectile-switch-project)
(define-key projectile-mode-map (kbd "C-c p r") 'projectile-discover-projects-in-search-path)
(provide 'init-project)
